DROP TABLE IF EXISTS team;
CREATE TABLE team (
	t_id VARCHAR(2) NOT NULL,
	teamName VARCHAR(50),
	countryCode VARCHAR(10),
	flagFilename VARCHAR(20),
	groupName VARCHAR(2),
	created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NULL DEFAULT NULL,
	CONSTRAINT pk_t_id PRIMARY KEY(t_id)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;