DROP TABLE IF EXISTS stadium;
CREATE TABLE stadium (
	s_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	stadiumName VARCHAR(50),
	city VARCHAR(50),
	capacity INTEGER,
	created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NULL DEFAULT NULL,
	CONSTRAINT pk_s_id PRIMARY KEY(s_id)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;