DROP TABLE IF EXISTS playerGroup;
CREATE TABLE playerGroup (
	pg_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	playerGroupName VARCHAR(50),
	created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NULL DEFAULT NULL,
	CONSTRAINT pk_pg_id PRIMARY KEY(pg_id)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;