DROP TABLE IF EXISTS player;
CREATE TABLE player (
	p_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	playerGroup_id INTEGER UNSIGNED NOT NULL,
	role_id INTEGER UNSIGNED NOT NULL,
	lastName VARCHAR(50),
	firstName VARCHAR(50),
	nickname VARCHAR(50),
	mobile VARCHAR(30),
	email VARCHAR(100),
	pword VARCHAR(100),
	disabled BOOLEAN,
	dateBetPaid DATE,
	created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NULL DEFAULT NULL,
	CONSTRAINT pk_p_id PRIMARY KEY(p_id),
	CONSTRAINT uk_email UNIQUE KEY(email),
	CONSTRAINT fk_player_playerGroup_id FOREIGN KEY (playerGroup_id)
		REFERENCES playerGroup(pg_id)
			ON DELETE RESTRICT
			ON UPDATE CASCADE,
	CONSTRAINT fk_player_role_id FOREIGN KEY (role_id)
		REFERENCES role(r_id)
			ON DELETE RESTRICT
			ON UPDATE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;