DROP TABLE IF EXISTS phase;
CREATE TABLE phase (
	ph_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	phaseName VARCHAR(50),
	created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NULL DEFAULT NULL,
	CONSTRAINT pk_ph_id PRIMARY KEY (ph_id)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;