DROP TABLE IF EXISTS fbmatchMeta;
CREATE TABLE fbmatchMeta (
    fbmM_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    fbmatch_id INTEGER UNSIGNED NOT NULL,
    descTeamHome VARCHAR(20),
    descTeamGuest VARCHAR(20),
	created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NULL DEFAULT NULL,
	CONSTRAINT pk_fbmM_id PRIMARY KEY (fbmM_id),
	CONSTRAINT fk_fbmatchMeta_fbmatch_id FOREIGN KEY (fbmatch_id)
		REFERENCES fbmatch(fbm_id)
			ON DELETE RESTRICT
			ON UPDATE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;